name: release

on:
  release:
    types: [ published ]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: |
          cd node-proxy
          npm install && npm run build
      - name: Upload assets
        uses: softprops/action-gh-release@v1
        with:
          files: node-proxy/build/*
          prerelease: false
          token: ${{ secrets.REPO_TOKEN }}
